import { Recipe } from "./types";

const now = Date.now();

function rid() {
  return Math.random().toString(36).slice(2, 10);
}

export const SEED_RECIPES: Recipe[] = [
  {
    id: "seed-chicken-rice-bowl",
    name: "Chicken rice bowl",
    mealType: "lunch",
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    difficulty: 1,
    emoji: "🍚",
    storageDays: 4,
    freezerFriendly: true,
    tags: ["Quick", "High protein", "Meal prep", "Leftover-friendly"],
    equipment: ["Rice cooker or pot", "Skillet"],
    ingredients: [
      { id: rid(), name: "chicken breast", quantity: 600, unit: "g", section: "Meat & seafood", note: "diced" },
      { id: rid(), name: "white rice", quantity: 2, unit: "cup", section: "Rice, pasta & grains" },
      { id: rid(), name: "broccoli", quantity: 1, unit: "piece", section: "Produce", note: "head, cut into florets" },
      { id: rid(), name: "soy sauce", quantity: 3, unit: "tbsp", section: "Sauces & seasonings" },
      { id: rid(), name: "garlic", quantity: 3, unit: "clove", section: "Produce" },
      { id: rid(), name: "olive oil", quantity: 2, unit: "tbsp", section: "Sauces & seasonings" },
    ],
    steps: [
      "Rinse the rice and start it cooking with 4 cups of water.",
      "Season the diced chicken with salt and pepper.",
      "Heat olive oil in a skillet over medium-high heat.",
      "Cook the chicken until golden and cooked through, about 8 minutes.",
      "Add minced garlic and soy sauce, toss for 1 minute.",
      "Steam or microwave the broccoli until bright green.",
      "Build bowls: rice, chicken, broccoli. Spoon pan sauce over the top.",
    ],
    createdAt: now,
  },
  {
    id: "seed-weeknight-pasta",
    name: "One-pot tomato pasta",
    mealType: "dinner",
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 20,
    difficulty: 1,
    emoji: "🍝",
    storageDays: 3,
    freezerFriendly: false,
    tags: ["One-pot", "Quick", "Low cleanup", "Leftover-friendly"],
    equipment: ["Large pot"],
    ingredients: [
      { id: rid(), name: "spaghetti", quantity: 400, unit: "g", section: "Rice, pasta & grains" },
      { id: rid(), name: "diced tomato", quantity: 1, unit: "can", section: "Canned & packaged" },
      { id: rid(), name: "garlic", quantity: 2, unit: "clove", section: "Produce" },
      { id: rid(), name: "olive oil", quantity: 2, unit: "tbsp", section: "Sauces & seasonings" },
      { id: rid(), name: "parmesan", quantity: 50, unit: "g", section: "Dairy & eggs" },
    ],
    steps: [
      "Add pasta, canned tomato, sliced garlic, oil, and 3 cups water to a pot.",
      "Bring to a boil, then simmer, stirring often, until pasta is tender (~12 min).",
      "Let the sauce reduce to coat the pasta.",
      "Finish with grated parmesan and black pepper.",
    ],
    createdAt: now,
  },
  {
    id: "seed-beef-stirfry",
    name: "Beef & pepper stir-fry",
    mealType: "dinner",
    servings: 3,
    prepMinutes: 15,
    cookMinutes: 12,
    difficulty: 2,
    emoji: "🥩",
    storageDays: 3,
    freezerFriendly: true,
    tags: ["High protein", "Quick", "Leftover-friendly"],
    equipment: ["Wok or large skillet"],
    ingredients: [
      { id: rid(), name: "beef strips", quantity: 450, unit: "g", section: "Meat & seafood" },
      { id: rid(), name: "bell pepper", quantity: 2, unit: "piece", section: "Produce" },
      { id: rid(), name: "onion", quantity: 1, unit: "piece", section: "Produce" },
      { id: rid(), name: "soy sauce", quantity: 3, unit: "tbsp", section: "Sauces & seasonings" },
      { id: rid(), name: "garlic", quantity: 2, unit: "clove", section: "Produce" },
      { id: rid(), name: "vegetable oil", quantity: 2, unit: "tbsp", section: "Sauces & seasonings" },
    ],
    steps: [
      "Slice peppers and onion. Mince garlic.",
      "Heat oil in a wok until shimmering.",
      "Sear beef in a single layer, 2 minutes, then remove.",
      "Stir-fry peppers and onion until crisp-tender.",
      "Return beef, add garlic and soy sauce, toss 1 minute.",
      "Serve over rice.",
    ],
    createdAt: now,
  },
  {
    id: "seed-training-wrap",
    name: "Training-day chicken wrap",
    mealType: "lunch",
    servings: 1,
    prepMinutes: 8,
    cookMinutes: 0,
    difficulty: 1,
    emoji: "🌯",
    storageDays: 1,
    freezerFriendly: false,
    tags: ["Training-day meal", "Quick", "Low cleanup"],
    equipment: [],
    ingredients: [
      { id: rid(), name: "tortilla wrap", quantity: 1, unit: "piece", section: "Bakery" },
      { id: rid(), name: "cooked chicken", quantity: 120, unit: "g", section: "Meat & seafood" },
      { id: rid(), name: "spinach", quantity: 1, unit: "cup", section: "Produce" },
      { id: rid(), name: "hummus", quantity: 2, unit: "tbsp", section: "Canned & packaged" },
    ],
    steps: [
      "Spread hummus across the tortilla.",
      "Layer spinach and sliced cooked chicken.",
      "Roll tightly, slice in half, and go.",
    ],
    createdAt: now,
  },
  {
    id: "seed-egg-fried-rice",
    name: "Egg fried rice",
    mealType: "dinner",
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 10,
    difficulty: 1,
    emoji: "🍳",
    storageDays: 2,
    freezerFriendly: false,
    tags: ["Quick", "One-pot", "Low cleanup", "Leftover-friendly"],
    equipment: ["Skillet"],
    ingredients: [
      { id: rid(), name: "cooked rice", quantity: 3, unit: "cup", section: "Rice, pasta & grains", note: "day-old works best" },
      { id: rid(), name: "eggs", quantity: 3, unit: "piece", section: "Dairy & eggs" },
      { id: rid(), name: "frozen peas", quantity: 1, unit: "cup", section: "Frozen" },
      { id: rid(), name: "soy sauce", quantity: 2, unit: "tbsp", section: "Sauces & seasonings" },
      { id: rid(), name: "vegetable oil", quantity: 1, unit: "tbsp", section: "Sauces & seasonings" },
    ],
    steps: [
      "Heat oil in a skillet over high heat.",
      "Scramble the eggs, then push to one side.",
      "Add rice and peas, breaking up clumps.",
      "Stir-fry until hot, add soy sauce, toss, and serve.",
    ],
    createdAt: now,
  },
  {
    id: "seed-overnight-oats",
    name: "Overnight oats",
    mealType: "breakfast",
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 0,
    difficulty: 1,
    emoji: "🥣",
    storageDays: 3,
    freezerFriendly: false,
    tags: ["Meal prep", "Quick"],
    equipment: ["Jar"],
    ingredients: [
      { id: rid(), name: "rolled oats", quantity: 0.5, unit: "cup", section: "Rice, pasta & grains" },
      { id: rid(), name: "milk", quantity: 0.5, unit: "cup", section: "Dairy & eggs" },
      { id: rid(), name: "banana", quantity: 1, unit: "piece", section: "Produce" },
    ],
    steps: [
      "Combine oats and milk in a jar.",
      "Top with sliced banana.",
      "Refrigerate overnight. Eat cold.",
    ],
    createdAt: now,
  },
];
